<?php

namespace Database\Factories;

use App\Models\Product;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

class ProductFactory extends Factory
{
    protected $model = Product::class;

    protected $productNames = [
        'Zanahoria',
        'Tomate',
        'Lechuga',
        'Miel',
        'Mermelada de fresa',
        'Arándanos',
        'Espinaca',
        'Pimiento',
        'Cebolla',
        'Ajo',
        'Pera',
        'Manzana',
        'Naranja',
        'Banana',
        'Uvas',
        'Melón',
        'Sandía',
        'Kiwi',
        'Papaya',
        'Durazno',
        'Frambuesa',
        'Brócoli',
        'Coliflor',
        'Apio',
        'Rábanos',
        'Calabaza',
        'Pepino',
        'Albahaca',
        'Cilantro',
        'Perejil',
        'Tomillo',
        'Romero',
        'Fresas',
        'Cereza',
        'Granada',
        'Higos',
        'Mango',
        'Chirimoya',
        'Guayaba',
        'Maracuyá',
        'Lima',
        'Limón',
        'Mandarina',
        'Coco',
        'Almendras',
        'Nueces',
        'Avellanas',
        'Pistachos',
        'Anacardos',
        'Aceitunas',
        'Espárragos',
        'Remolacha',
        'Batata',
        'Endibia',
        'Escarola',
        'Repollo',
        'Coles de Bruselas',
        'Berenjena',
        'Calabacín',
        'Chayote',
        'Jengibre',
        'Cúrcuma',
        'Acelga',
        'Berro',
        'Setas',
        'Champiñones',
        'Porotos',
        'Lentejas',
        'Garbanzos',
        'Quinoa',
        'Arroz integral',
        'Trigo sarraceno',
        'Cuscús',
        'Mijo',
        'Sésamo',
        'Chía',
        'Linaza',
        'Castañas',
        'Macadamias',
        'Piñones',
        'Cacahuetes',
        'Dátiles',
        'Ciruelas',
        'Albaricoque',
        'Moras',
        'Grosellas',
        'Tamarindo',
        'Camu camu',
        'Aguacate',
        'Pepitas de calabaza',
        'Semillas de girasol',
        'Aceite de oliva',
        'Aceite de coco',
        'Yogur natural',
        'Queso fresco',
        'Leche de almendras',
        'Tofu',
        'Tempeh'
    ];

    public function definition(): array
    {
        return [
            'name' => $this->faker->unique()->randomElement($this->productNames),
            'description' => $this->faker->sentence(6, true) . ' Fresco y de alta calidad, ideal para tu cocina.',
            'quantity' => $this->faker->numberBetween(0, 100),
            'quantity_type' => $this->faker->randomElement(['kilo', 'litro', 'unidad', 'bolsa', 'caja']),
            'price' => $this->faker->randomFloat(2, 0.5, 20),
            'status' => $this->faker->randomElement(['activo', 'inactivo']),
            'user_id' => User::factory(),
            'allow_fractional' => $this->faker->boolean(),
            'category_id' => $this->faker->numberBetween(1, 7),
        ];
    }
}
